--LAB 6
--DATE Function


--PART-A

--1.
SELECT GETDATE() AS 'TODAY_DATE';

--2.
SELECT GETDATE() + 365;

--3.
SELECT CONVERT (VARCHAR,GETDATE());


--4.
SELECT CONVERT (VARCHAR,GETDATE(),106);

--5.
SELECT CONVERT (VARCHAR,GETDATE(),7);

--6.
SELECT DATEDIFF(MONTH,'31-DEC-08','31-MAR-09');--INTERVAL VARIABLE,HIGHER VALUE,LOW VALUE

--7.
SELECT DATEDIFF(YEAR,'25-JAN-12','14-SEP-10');

 --8.
SELECT DATEDIFF(HOUR,'25-JAN-12 7:00 PM','26-JAN-12 10:30 AM');

--9.
SELECT DAY('12-MAY-16') AS DAY,MONTH('12-MAY-16') AS MONTH,YEAR('12-MAY-16') AS YEAR;

--10.
SELECT DATEADD(YEAR,5,GETDATE());

--11.
SELECT DATEADD(MONTH,-2,GETDATE());

--12.
--Using datename() 
SELECT DATENAME(MONTH,GETDATE());
--Using datepart()
SELECT DATEPART(MONTH,GETDATE());

--13.
SELECT EOMONTH(GETDATE()); --EO = END OF MONTH


--14.
SELECT DATEDIFF(YEAR,'09-DEC-2004',GETDATE()) AS Yrs;
SELECT DATEDIFF(MONTH,'09-DEC-2004',GETDATE()) AS Months; 



--PART-B

CREATE TABLE EMP_DETAIL
(
	EmpNo INT,
	EmpName VARCHAR(25),
	JoiningDate DATETIME,
	Salary DECIMAL(8,2),
	City VARCHAR(25)
)

INSERT INTO EMP_DETAIL
VALUES
(101,'Keyur','15-JAN-02', 12000.00,'Rajkot'),
(102,'Hardik','15-FEB-04', 14000.00,'Ahmedabad'),
(103, 'Kajal','14-MAR-06',15000.00,'Baroda'),
(104, 'Bhoomi','23-JUN-05',12500.00,'Ahmedabad'),
(105, 'Harmit','15-FEB-04',14000.00,'Rajkot'),
(106,'Jay','12-MAR-07',12000.00,'Surat')


--1.
	SELECT DATEADD(DAY,365,JoiningDate) FROM EMP_DETAIL

--2.
	SELECT CONVERT(VARCHAR(25), JoiningDate, 109) FROM EMP_DETAIL

--3.
	SELECT CONVERT(VARCHAR(25), JoiningDate, 106) FROM EMP_DETAIL

--4.
	SELECT CONVERT(VARCHAR(25), JoiningDate, 107) FROM EMP_DETAIL

--5.
	SELECT DATEDIFF(MONTH,JoiningDate,'31-MAR-09') FROM EMP_DETAIL

--6.
	SELECT DATEDIFF(YEAR,JoiningDate,'12-SEP-10') FROM EMP_DETAIL

--PART-C

--1.
	SELECT DATEPART(DAY,JoiningDate),DATEPART(MONTH,JoiningDate),DATEPART(YEAR,JoiningDate) FROM EMP_DETAIL

--2.
	SELECT DATEADD(YEAR,5,JoiningDate) FROM EMP_DETAIL

--3.
	SELECT DATEADD(MONTH,-2,JoiningDate) FROM EMP_DETAIL

--4.
	SELECT DATEPART(MONTH,JoiningDate),DATENAME(MONTH,JoiningDate) FROM EMP_DETAIL

--5.
	SELECT DATEDIFF(YEAR,'09-DEC-2004',GETDATE()) AS Yrs;
    SELECT DATEDIFF(MONTH,'09-DEC-2004',GETDATE()) AS Months;
	
	