--USE CSE_3B_385
--LAB 8
CREATE TABLE SALES_DATA(
	REGION VARCHAR(50),
	PRODUCT VARCHAR(50),
	SALES_AMOUNT INT,
	YEAR INT
);

INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('NORTH AMERICA','WATCH',1500,2023);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('EUROP','MOBILE',1200,2023);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('ASIA','WATCH',1800,2023);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('NORTH AMERICA','TV',900,2024);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('EUROP','WATCH',2000,2024);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('ASIA','MOBILE',1000,2024);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('NORTH AMERICA','MOBILE',1600,2023);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('EUROPE','TV',1500,2023);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('ASIA','TV',1100,2024);
INSERT INTO SALES_DATA (REGION,PRODUCT,SALES_AMOUNT,YEAR) VALUES ('NORTH AMERICA','WATCH',1700,2024);

SELECT * FROM SALES_DATA


--------PART A-------------
--1. Display Total Sales Amount by Region.
SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA GROUP BY REGION 

--2. Display Average Sales Amount by Product
SELECT AVG(SALES_AMOUNT),PRODUCT FROM SALES_DATA GROUP BY PRODUCT

--3. Display Maximum Sales Amount by Year
SELECT MAX(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR

--4.Display Minimum Sales Amount by Region and Year
SELECT MIN(SALES_AMOUNT),REGION,YEAR FROM SALES_DATA GROUP BY REGION,YEAR

--5.Count of Products Sold by RegionSELECT COUNT(PRODUCT),REGION FROM SALES_DATA GROUP BY REGION

--6.Display Sales Amount by Year and Product
SELECT COUNT(SALES_AMOUNT),PRODUCT,YEAR FROM SALES_DATA GROUP BY PRODUCT,YEAR

--7.Display Regions with Total Sales Greater Than 5000SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000--8. Display Products with Average Sales Less Than 10000SELECT AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000--9. Display Years with Maximum Sales Exceeding 500SELECT MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING MAX(SALES_AMOUNT)>500

--10. Display Regions with at Least 3 Distinct Products Sold. 
SELECT COUNT(DISTINCT PRODUCT) FROM SALES_DATA GROUP BY REGION HAVING COUNT(DISTINCT PRODUCT)>=3

--11. . Display Years with Minimum Sales Less Than 1000SELECT MIN(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING COUNT(SALES_AMOUNT)<1000

--12. Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount
SELECT SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR=2023 GROUP BY REGION ORDER BY SUM(SALES_AMOUNT) DESC

---------PART B-----------
--1. Display Count of Orders by Year and Region, Sorted by Year and Region
SELECT COUNT(YEAR),COUNT(REGION) FROM SALES_DATA GROUP BY YEAR,REGION ORDER BY COUNT(YEAR),COUNT(REGION) DESC

--2. Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region
SELECT MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION

--3. Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending
SELECT SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)<1000 ORDER BY YEAR DESC

--4. Display Top 3 Regions by Total Sales Amount in Year 2024
SELECT TOP 3 SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR=2024 GROUP BY REGION ORDER BY SUM(SALES_AMOUNT) DESC

-----PART C---------
--1. Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name
SELECT PRODUCT,AVG(Sales_Amount) FROM SALES_DATA  GROUP BY PRODUCT HAVING AVG(Sales_Amount) BETWEEN 1000 AND 2000 ORDER BY PRODUCT

--2. Display Years with More Than 5 Orders from Each Region
SELECT YEAR, COUNT(Sales_Amount) FROM SALES_DATA GROUP BY REGION,YEAR HAVING COUNT(Sales_Amount) > 5

--3. Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.
SELECT REGION,AVG(Sales_Amount) FROM SALES_DATA WHERE YEAR= 2023 GROUP BY REGION,Sales_Amount HAVING AVG(Sales_Amount) > 1500 ORDER BY Sales_Amount DESC

--4. Find out region wise duplicate product.
SELECT REGION,PRODUCT FROM SALES_DATA GROUP BY REGION,PRODUCT HAVING COUNT(REGION) >= 2

--5. Find out region wise highest sales amount.
SELECT REGION,MAX(Sales_Amount) FROM SALES_DATA GROUP BY REGION 