--LAB 4
--Alter Operation
--PART-A

--1 
ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20),PINCODE INT;
--2 
ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35);
--3 
ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT;
--4 
EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO';
SELECT * FROM DEPOSIT;
--5
ALTER TABLE DEPOSIT
DROP COLUMN CITY;
--6 
EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL';

--PART B 
--1 
EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE';
--2
ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE;
--3 
EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CustomerName';

--PART C
CREATE TABLE STUDENT_DETAIL(
	ENROLLMENT_NO VARCHAR(20),
	NAME VARCHAR(25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
);
--1
ALTER TABLE STUDENT_DETAIL
ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL;
--2 
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN NAME VARCHAR(35);
--3
ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT;
--4 
EXEC SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO';
SELECT * FROM STUDENT_DETAIL
--5
ALTER TABLE STUDENT_DETAIL
DROP COLUMN CITY;
--6
EXEC SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER';


--DELETE, Truncate, Drop Operation
--PART A

--1 
DELETE FROM DEPOSIT_DETAIL
WHERE AMOUNT>=4000;
--2 
DELETE FROM DEPOSIT_DETAIL
WHERE BNAME='CHANDI';
--3 
DELETE FROM DEPOSIT_DETAIL
WHERE ANO>105
--4 
TRUNCATE TABLE DEPOSIT_DETAIL;
--5 
DROP TABLE DEPOSIT_DETAIL;

--PART-B
CREATE TABLE EMPLOYEE_MASTER(
	EMPNO INT,
	EMPNAME VARCHAR(25),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);
INSERT INTO EMPLOYEE_MASTER(EMPNO,EMPNAME,JOININGDATE,SALARY,CITY) VALUES 
(101,'KEYUR','2002-01-05',12000.00,'RAJKOT'),
(102,'HARDIK','2004-02-15',14000.00,'AHMEDABAD'),
(103,'KAJAL','2006-03-14',15000.00,'BARODA'),
(104,'BHOOMI','2005-06-23',12500.00,'AHMEDABAD'),
(105,'HARMIT','2004-02-15',14000.00,'RAJKOT'),
(106,'MITESH','2001-09-25',5000.00,'JAMNAGAR'),
(107,'MEERA',NULL,7000.00,'MORBI'),
(108,'KISHAN','2003-02-06',10000.00,NULL);

